version: '3.4'
services:
  api-gateway:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
    # command: sh
    ports:
      - "8080:8080"
    tty: true


networks:
  default:
    external:
      name: fishapp-net
